### ISSUE TITLE
[Improvement] Addittional properties hide

### ISSUE THREAD

**Issue by Unb0rn** [sidex15/ksu_module_susfs#1]
While testing this module I found that Shamiko still behaves a little bit better...
Bootloader state is being spoofed with the latest beta tricky store for me

Hunter (v5.9.6, 2024-09-06) detects unlocked bootloader (reports orange), while Momo doesn't - the only place I found was in `/proc/cmdline` the kernel parameter passed was `androidboot.verifiedbootstate=orange`, getprops still seems to be clean. Ordinary apps shouldn't have the access to cmdline, so it probably get this from somewhere else and only Shamiko knows where.

Another thing, after adding TrickyStore module I started getting "Partition Modified" in Native Test v27. After researching a bit I found [this](https://xdaforums.com/t/tricky-store-bootloader-keybox-spoofing.4683446/post-89699970). TL/DR: setting `ro.boot.vbmeta.digest` to the Verified boot hash value found in Key Attestation app should resolve the issue
Looks like simonpunk left us the function `susfs_hexpatch_props` in utils.sh, but I have no idea on how to get this verified boot hash programmatically.

**Comment by sidex15** [comment]
Well, Shamiko is using service.sh for its props and stuff. I'll include that script in the next reversion as soon as possible.
As for the verified boot hash since there's no way to automate/generate a verified boot hash, then the only workaround is to generate a directory with a blank text file so that you can input the verified boot hash there and reboot.

**Comment by sidex15** [comment]
Released and Fixed on Revision 3

**Comment by Unb0rn** [comment]
Cool! Thanks)
One more thing - is there any chance discussions will be enabled for this repo?
I have some input yet I don't want to create another issue

I'm using iodeOS (it's a microG-enabled  LOS fork) and the latest changes fixed one thing but broke another)
using `enable_sus_su` seems to resolve the "Abnormal environment" in Native Test and in Holmes, but at the same time it breaks SafetyNet completely (SPIC or microG test) and that's pretty strange

**Comment by sidex15** [comment]
> Cool! Thanks) One more thing - is there any chance discussions will be enabled for this repo? I have some input yet I don't want to create another issue
> 
> I'm using iodeOS (it's a microG-enabled LOS fork) and the latest changes fixed one thing but broke another) using `enable_sus_su` seems to resolve the "Abnormal environment" in Native Test and in Holmes, but at the same time it breaks SafetyNet completely (SPIC or microG test) and that's pretty strange

IDK about that microg one as I use TS and play integrity fix for passing safetynet and play integrity. idk also if possible if tricky store can do on microg when it put to target.txt
