### ISSUE TITLE
How to make HMA work with this module?

### ISSUE THREAD

**Issue by hoang1007** [sidex15/ksu_module_susfs#11]
Can you provide more detail instructions how to use HMA with this module? I do not know how to make LSposed works since zygote is hidden.

**Comment by sidex15** [comment]
I think LSPosed will work without any issues did you try Irena, Jingmatrix, and Internal test ones?

**Comment by hoang1007** [comment]
Thank you! I thought susfs can replace Zygisk. I installed ZygiskNext and new Lsposed works
