### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by xnnnsets** [sidex15/ksu_module_susfs#13]
/logs/susfs.log is empty/missing

**Comment by xnnnsets** [comment]
can this be run on kernel 4.19 ?

**Comment by sidex15** [comment]
The KernelSU kernel must have SUSFS patched into the kernel.

If you're the kernel maintainer refer to this original susfs repo for guides on how to patch SUSFS to your kernel https://gitlab.com/simonpunk/susfs4ksu/

If you're an end user without experience building kernels, Contact your kernel maintainer to patch susfs to your kernel.

**Comment by xnnnsets** [comment]
I already patch to susfs to kernel https://gitlab.com/simonpunk/susfs4ksu/ branch 4.19, but to make sure susfs is working properly how to check it

**Comment by sidex15** [comment]
> I already patch to susfs to kernel https://gitlab.com/simonpunk/susfs4ksu/ branch 4.19, but to make sure susfs is working properly how to check it

install the module you'll see if the susfs is supported in the module description...

**Comment by xnnnsets** [comment]
![Screenshot_20241212_232752_KernelSU](https://github.com/user-attachments/assets/9674a24b-c42a-4bc7-9cae-6c036c77aae4)

Owh working sorry
Thanks😅
