### ISSUE TITLE
SuSFS patched kernel but not enabled. 

### ISSUE THREAD

**Issue by PlatFlat** [sidex15/ksu_module_susfs#20]
I have a SuSFS patched kernel but it seems like it doesn't create the susfs_active file thus ksu_module_susfs is unable to run.

However upon changing [line 16](https://github.com/sidex15/ksu_module_susfs/blob/86a5f09c1b5adf034b7168daec6870cec8bc3b64/boot-completed.sh#L16C1-L16C46), from:

`if [ -f $tmpfolder/logs/susfs_active ] ; then`

to

`if dmesg | grep -q "susfs:"; then`

This works. What it is causing this issue? low log buffer size?

I am using v1.4.2 with log KSU_SUSFS_ENABLE_LOG logs off.

**Comment by sidex15** [comment]
the line you've workaround with is the same as the post-fs.sh line:
`dmesg | grep -q "susfs:" > /dev/null && touch $tmpfolder/logs/susfs_active`
it probably either it didn't read the /debug_ramdisk/susfs4ksu/logs/susfs_active
or the log buffers of dmesg and printk are low
try to set `CONFIG_PRINTK_EXTRA_LOGBUF_SHIFT` in defconfig to 20
also check the logs in /debug_ramdisk/susfs4ksu/logs

**Comment by backslashxx** [comment]
i can offer a small override for this
might need a shell command or if the webui decides to offer it
its just that its a bit hard to support massively different setups

**Comment by backslashxx** [comment]
this is live
```
touch /data/adb/susfs4ksu/susfs_force_override
```

**Comment by sidex15** [comment]
It's not fixed with Revision 12
