### ISSUE TITLE
Can't you coexist with a hidden root module like shamiko?

### ISSUE THREAD

**Issue by qwerzxcva** [sidex15/ksu_module_susfs#23]
Can't coexist with a hidden root module like shamiko? Does it have the functionality of a module like shamiko?
Can I support Abatch, if I patch ksu boot to Abatch and replace boot on my system, Is it valid and can you use the module?

**Comment by backslashxx** [comment]
the module isnt responsible for this
if you build your own kernel, upstream ha s asmall change you can backport to your build

https://gitlab.com/simonpunk/susfs4ksu/-/commit/b25d11581dc03e12eae537564d10c4f17142b901
