### ISSUE TITLE
[QUESTION] Does it compatible with Kernel 6.1 KernelSU LKM mode?

### ISSUE THREAD

**Issue by dathtd119** [sidex15/ksu_module_susfs#3]
Hi, I installed KernelSU on my phone, the details:

- Android 14 (Color OS) Kernel 6.1
- KernelSU running LKM mode

Will it be compatible with my kernel?

Also, please make a discussion tab for further questions like this, thanks so much.

**Comment by sidex15** [comment]
The KernelSU kernel must have SUSFS patched into the kernel.

If you're the kernel maintainer refer to this original susfs repo for guides on how to patch SUSFS to your kernel https://gitlab.com/simonpunk/susfs4ksu/

If you're an end user without experience building kernels, Contact your kernel maintainer to patch susfs to your kernel.

I'll make a discussion thread of this one soon thanks.
