### ISSUE TITLE
using module breaks PIF device integrity

### ISSUE THREAD

**Issue by calebchongc** [sidex15/ksu_module_susfs#8]
Current setup is using crDroid A15 on P8 (shiba).
Other modules: only playintegrityfix and zygisknext, no lsposed or other modules.
I flashed susfs ksu kernel from AnyKernel3-lz4-android14-5.15.148_2024-05.zip and installed this module, which changes integrity back to basic. Uninstalling module makes the integrity go back to device, so pretty sure it's something in susfs/module where integrity is being broken.

**Comment by sidex15** [comment]
I assume you're using sus_su since you're in gki mode... try to turn off the sus_su on boot switches in the webui check to see if integrity works...
as for my side, pif fork is still working...

**Comment by sidex15** [comment]
also what's your setup in the WebUI?

**Comment by calebchongc** [comment]
![photo_2024-12-09_20-41-22](https://github.com/user-attachments/assets/1192a27a-c2a6-44a9-b0e9-929afcd469ef)
![photo_2024-12-09_20-41-19](https://github.com/user-attachments/assets/f5d83484-bb2e-4053-9f00-866fa005a555)
I tried turning everything off and am still getting basic integrity..

**Comment by sidex15** [comment]
what about the sus mount did you try to remove all paths there as well?

**Comment by calebchongc** [comment]
I set everything to just some comment strings and still went from device -> basic integrity 🤔 
![photo_2024-12-10_17-22-38](https://github.com/user-attachments/assets/bdde6f0b-0bb1-4ef9-81ae-91241c9ee144)

**Comment by sidex15** [comment]
could you give me all of the susfs logs in /debug_ramdisk/susfs4ksu/logs?

**Comment by calebchongc** [comment]
Somehow trying to copy out the files doesn't work and I get permission errors, but I used adb shell to cat the log files:
```
cat /debug_ramdisk/susfs4ksu/logs/susfs1.log

susfs4ksu/post-fs-data: [logging_initialized]
susfs4ksu/service: [hide_vendor_sepolicy]
[update_sus_kstat]: susfs4ksu/service
[sus_mount]: susfs4ksu/service

cat /debug_ramdisk/susfs4ksu/logs/susfs.log

[    3.668957][  T812] susfs:[0][812][susfs_auto_add_sus_ksu_default_mount] set SUS_MOUNT inode state for default KSU mount path '/data/adb/modules/'
[    3.682742][  T812] susfs:[0][812][susfs_auto_add_sus_ksu_default_mount] set SUS_MOUNT inode state for default KSU mount path '/debug_ramdisk'
[   18.480816][ T3065] susfs:[0][3065][susfs_auto_add_sus_bind_mount]skip setting SUS_MOUNT inode state for source bind mount path '/debug_ramdisk/susfs4ksu/vendor_sepolicy.cil'
```

**Comment by HpNoTiQ56** [comment]
Are you using pig in basic of full mode?

**Comment by sidex15** [comment]
> Somehow trying to copy out the files doesn't work and I get permission errors, but I used adb shell to cat the log files:
> 
> ```
> cat /debug_ramdisk/susfs4ksu/logs/susfs1.log
> 
> susfs4ksu/post-fs-data: [logging_initialized]
> susfs4ksu/service: [hide_vendor_sepolicy]
> [update_sus_kstat]: susfs4ksu/service
> [sus_mount]: susfs4ksu/service
> 
> cat /debug_ramdisk/susfs4ksu/logs/susfs.log
> 
> [    3.668957][  T812] susfs:[0][812][susfs_auto_add_sus_ksu_default_mount] set SUS_MOUNT inode state for default KSU mount path '/data/adb/modules/'
> [    3.682742][  T812] susfs:[0][812][susfs_auto_add_sus_ksu_default_mount] set SUS_MOUNT inode state for default KSU mount path '/debug_ramdisk'
> [   18.480816][ T3065] susfs:[0][3065][susfs_auto_add_sus_bind_mount]skip setting SUS_MOUNT inode state for source bind mount path '/debug_ramdisk/susfs4ksu/vendor_sepolicy.cil'
> ```
try to contact me through email in my bio. I could give you the test version.
